In [170]:
import rpy2
import pandas as pd
import numpy as np
#import rpy2POC

import rpy2.robjects as robjects
from rpy2.robjects.vectors import DataFrame
from rpy2.robjects import pandas2ri

pandas2ri.activate()


#import os 
#cwd = os.getcwd()
#print(cwd)

r_source = rpy2.robjects.r['source']



R_Hist_perf = DataFrame.from_csvfile('transactions_data.csv',header=False,sep=',')
R_Hist_space_climate_info = DataFrame.from_csvfile('fixture_data.csv',header=False,sep=',')
R_Future_Space_Entry_Data = DataFrame.from_csvfile('Entry.Future Space.csv',header=True,sep=",")
R_Brand_Exit = DataFrame.from_csvfile('exit_data.csv',header=False,sep=',')
histPerf=pd.read_csv('transactions_data.csv',header=0).set_index('Store')
histSpace=pd.read_csv('fixture_data.csv',header=None)
futureSpace=pd.read_csv('Entry.Future Space.csv')
brandExit=pd.read_csv('exit_data.csv')
print(histPerf.index)
Categories=histSpace.loc[0][3::].reset_index(drop=True).rename('Categories').astype(str)
Stores=histSpace[0].reindex(histSpace.index.drop([0,1])).reset_index(drop=True).rename('Stores').astype(int)

Float64Index([   nan,    7.0,    8.0,    9.0,   10.0,   11.0,   14.0,   17.0,
                18.0,   19.0,
              ...
              1502.0, 1503.0, 1504.0, 1506.0, 1507.0, 1508.0, 1510.0, 1515.0,
              1516.0, 1517.0],
             dtype='float64', name='Store', length=1147)

In [178]:
histSpace=pd.read_csv('fixture_data.csv',header=None)
histSpace.loc[0][3::]
histSpace.columns=histSpace.iloc[0].values
histSpace.drop(histSpace.index[[0,1]],axis=0,inplace=True)
histSpace['Store'].astype(int)
histSpace.set_index('Store',drop=True,inplace=True)
print(histSpace.index)
print(histSpace.head())

def primMung(df):
    df.columns=df.iloc[0].values
    df.drop(df.index[[0,]],axis=0,inplace=True).set_index(histSpace.Store.values.astype(int),inplace=True)

Index(['7', '8', '9', '10', '11', '14', '17', '18', '19', '25',
       ...
       '1502', '1503', '1504', '1506', '1507', '1508', '1510', '1515', '1516',
       '1517'],
      dtype='object', name='Store', length=1146)
      Climate VSG  APT 9 CHAPS CROFT & BARROW GLORIA VANDERBILT  \
Store
7        COLD   SM     5     3           10.5                 2
8        COLD   ST     5     3              9                 2
9        COLD   SM     5     3              9                 2
10       COLD   ST     5     3              9                 2
11       COLD   SM     5     3              9                 2

      JENNIFER LOPEZ  LEE SONOMA TEKGEAR
Store
7                  3  1.5      6     5.5
8                  3  1.5      5     3.5
9                  2  1.5      5     3.5
10                 3  1.5      5     3.5
11                 3  1.5      5     3.5

In [139]:
histSpace.set_index('Store')

,Climate,VSG,APT 9,CHAPS,CROFT & BARROW,GLORIA VANDERBILT,JENNIFER LOPEZ,LEE,SONOMA,TEKGEAR
Store,,,,,,,,,,
7,COLD,SM,5,3,10.5,2,3,1.5,6,5.5
8,COLD,ST,5,3,9,2,3,1.5,5,3.5
9,COLD,SM,5,3,9,2,2,1.5,5,3.5
10,COLD,ST,5,3,9,2,3,1.5,5,3.5
11,COLD,SM,5,3,9,2,3,1.5,5,3.5
14,COLD,SM,5,3,9,2,2,1.5,5,3.5
17,COLD,ST,5,3,9,2,3,1.5,5,3.5
18,COLD,ST,5,3,10.5,2,3,1.5,6,5.5
19,COLD,SM,5,2,9,2,2,1.5,5,3.5
25,COLD,LG,5,3,9,2,2,1.5,5,3.5
31,COLD,ST,5,3,9,2,3,1.5,5,3.5
32,COLD,ST,5,2,9,2,3,1.5,5,3.5
33,COLD,LG,5,3,9,2,2,1.5,5,3.5
34,COLD,ST,5,2,9,2,3,1.5,5,3.5
35,COLD,ST,5,3,9,2,2,1.5,5,3.5
37,COLD,LG,5,3,9,2,3,1.5,5,3.5
39,COLD,ST,5,3,9,2,3,1.5,5,3.5
41,COLD,ST,5,3,10.5,2,3,1.5,6,5.5
43,COLD,SM,5,2,9,2,2,1.5,5,3.5
48,COLD,ST,5,3,9,2,2,1.5,5,3.5
49,COLD,SM,5,3,9,2,2,1.5,5,3.5
52,COLD,SM,5,3,9,2,2,1.5,5,3.5
54,COLD,SM,5,3,10.5,2,3,1.5,6,5.5
55,COLD,LG,5,3,9,2,2,1.5,5,3.5
57,COLD,SM,5,2,9,2,2,1.5,5,3.5
59,COLD,SM,5,2,9,2,2,1.5,5,3.5
60,COLD,ST,5,3,9,2,2,1.5,5,3.5
62,COLD,SM,5,3,9,2,3,1.5,5,3.5
63,COLD,ST,5,2,9,2,2,1.5,5,3.5
64,COLD,LG,5,3,9,2,2,1.5,5,3.5
...,...,...,...,...,...,...,...,...,...,...
1466,COLD,SM,4,2,7.5,1.5,2,1,4,3
1467,COLD,SM,4,2,7.5,1.5,2,1,4,3
1468,COLD,SM,4,2,7.5,1.5,2,1,4,3
1469,COLD,SM,4,2,7.5,1.5,2,1,4,3
1470,COLD,SM,4,2,7.5,1.5,2,1,4,3
1473,COLD,SM,4,2,7.5,1.5,2,1,4,3
1474,COLD,SM,4,2,7.5,1.5,2,1,4,3
1476,COLD,ST,5,2,9,2,2,1.5,5,3.5
1480,COLD,SM,4,2,7.5,1.5,2,1,4,3
1481,COLD,SM,5,2,9,2,2,1.5,5,3.5
1484,COLD,SM,5,2,9,2,2,1.5,5,3.5
1487,COLD,SM,4,2,7.5,1.5,2,1,4,3
1492,COLD,SM,4,2,7.5,1.5,2,1,4,3
1493,COLD,SM,4,2,7.5,1.5,2,1,4,3
1494,COLD,SM,5,3,9,2,2,1.5,5,3.5
1497,COLD,SM,4,2,7.5,1.5,2,1,4,3
1498,COLD,SM,4,2,7.5,1.5,2,1,4,3
1499,COLD,SM,4,2,7.5,1.5,2,1,4,3
1500,COLD,SM,5,2,9,2,2,1.5,5,3.5
1501,COLD,SM,4,2,7.5,1.5,2,1,4,3
1502,COLD,SM,5,2,9,2,2,1.5,5,3.5
1503,COLD,SM,4,2,7.5,1.5,2,1,4,3
1504,COLD,SM,4,2,7.5,1.5,2,1,4,3
1506,COLD,SM,4,2,7.5,1.5,2,1,4,3
1507,COLD,SM,4,2,7.5,1.5,2,1,4,3
1508,COLD,SM,4,2,7.5,1.5,2,1,4,3
1510,COLD,SM,4,2,7.5,1.5,2,1,4,3
1515,COLD,SM,4,2,7.5,1.5,2,1,4,3
1516,COLD,SM,4,2,7.5,1.5,2,1,4,3
1517,COLD,SM,4,2,7.5,1.5,2,1,4,3

In [154]:
histSpace.loc[0][3::]

KeyError: 'the label [0] is not in the [index]'

In [105]:
def primaryMung(df):
    df.columns = df.iloc[0]
    # print('columns')
    # print(df.columns)
#     df.reindex(df.index.drop(0))
#     print(df.head())
    df.set_index('Store')
    #     df.drop(df.index[[0]]).set_index("Store")
#     print(df.index)
    return df
primaryMung(histSpace)


# histPerf.rename(columns=histPerf.iloc[0],inplace=True)

# histPerf.rename(columns=lambda x: x.iloc[0], inplace=True)
# print(colNames)
# print(histPerf.columns)
# histPerf.columns=colNames
# print(histPerf.columns)
# colNames=histPerf.columns
# print(histPerf.drop(histPerf.index[[0]]).set_index("Store"))
# print(histPerf.index)

KeyError: 'Store'

In [2]:
#conversion Python to R, doesn't work
Hist_perf = pandas2ri.py2ri(P_Hist_perf)

NameError: name 'P_Hist_perf' is not defined

In [8]:

#Hist_space_climate_info = pandas2ri.py2ri(P_Hist_space_climate_info) 
#Future_Space_Entry_Data = pandas2ri.py2ri(P_Future_Space_Entry_Data) 
#Brand_Exit = pandas2ri.py2ri(P_Brand_Exit)


# Takes in 4 R data frames and a string, outputs Python data frame
def rpy2_data_merging(R_Hist_perf,R_Hist_space_climate_info,R_Future_Space_Entry_Data,R_Brand_Exit,optimizationType):
############## Data Merging ##############
    try:
        
        
        # Update: reading in original R objects, so we don't have to convert pi2ri
        # KB Convert python fed dataframes with 2 rows header into R dataframes with 2 rows header    
        #R_Hist_perf = pandas2ri.py2ri(P_Hist_perf)
        #R_Hist_space_climate_info = pandas2ri.py2ri(P_Hist_space_climate_info) 
        #R_Future_Space_Entry_Data = pandas2ri.py2ri(P_Future_Space_Entry_Data) 
        #R_Brand_Exit = pandas2ri.py2ri(P_Brand_Exit)
        
        # Parameter variable that used to be defined in the R code
        optimType = optimizationType

        # Source the R file into memory so it can be used
        r_source('Data_Merging_function_8_10_v4.R')

        # robjects.globalenv gives access to any global variable and functions from all sourced R scripts
        # The main function in the data merging code is called 'Data_merge', so we grab that function and store it into
        # a local python variable.  The variable can then be used to call the R function
        r_data_merge = rpy2.robjects.globalenv['Data_merge']
        
        # Call the R function (that's stored as a python variable).  Since there is only one object returned
        # it can be returned as normal and stored into a python variable
        # Here, the resulting return is in the form of an R DataFrame
        r_big_master_data = r_data_merge(R_Hist_perf,R_Hist_space_climate_info,R_Future_Space_Entry_Data,R_Brand_Exit,optimType)
        
        # KB Convert resulting R Dataframe back to pandas dataframe
        p_big_master_data=pandas2ri.ri2py(r_big_master_data)
        return p_big_master_data
    except:
        print("Data merging failed :(")
    return

# a=rpy2_data_merging(histPerf,R_Hist_space_climate_info,R_Future_Space_Entry_Data,R_Brand_Exit,"Regular")
a=rpy2_data_merging(histPerf,histSpace,futureSpace,brandExit,"Regular")

type(a)

a.head()

Changing in

Hist_perf1



From:
 Store

To:
 Cat





Changing in

Hist_perf1



From:
 variable

To:
 Store





Changing in

HSCI1



From:
 variable

To:
 Cat





Changing in

Hist_perf_space







From:
 Cat
 space
 Sales $
 Sales Units
 Profit $

To:
 Product
 Space
 Sales
 Units
 Profit

,Store,Climate,VSG,Product,Space,Sales,Units,Profit,Exit_Flag,Future Space,Entry Space,BOH $,BOH Units,CC Count w/ BOH,Profit %,Receipts $,Receipts Units
1,10,COLD,ST,APT 9,5,32945.22,1933,12722.859,0.0,33,0.0,35013.93333,838,133.5,0.386182244,84136,1878
2,10,COLD,ST,CHAPS,3,20381.34,1004,1283.09,0.0,33,0.0,38685.65,712.5,66.5,0.062954153,49174,746
3,10,COLD,ST,CROFT & BARROW,9,89958.93,6866,36035,0.0,33,0.0,82177.89667,2412.166667,228.3333333,0.400571683,202374,5746
4,10,COLD,ST,GLORIA VANDERBILT,2,15508.95,710,5375.49,0.0,33,0.0,13568.63,323,37.33333333,0.34660567,33358.26,774
5,10,COLD,ST,JENNIFER LOPEZ,3,14646.37,594,7418.786,0.0,33,0.0,19395.96667,350.3333333,59.16666667,0.506527283,39976,705